<?php
	$link = mysqli_connect('localhost','root','','db_rskgm_rekap');        
    
    $total1Umum=0;
    $total2Umum=0;
    $total3Umum=0;
    $total4Umum=0;
    $total5Umum=0;
    $total6Umum=0;
    $total7Umum=0;
    $total8Umum=0;
    $total9Umum=0;
    $total10Umum=0;
    $total11Umum=0;
    $total12Umum=0;
    $total13Umum=0;
    $total14Umum=0;
    $total15Umum=0;
    $total16Umum=0;
    $total17Umum=0;
    $total18Umum=0;
    $total19Umum=0;
    $total20Umum=0;
    $total21Umum=0;
    $total22Umum=0;
    $total23Umum=0;
    $total24Umum=0;
    $total25Umum=0;
    $total26Umum=0;
    $total27Umum=0;
    $total28Umum=0;
    $total29Umum=0;
    $total30Umum=0;
    $total31Umum=0;
    $total32Umum=0;
    $total33Umum=0;
    $total34Umum=0;
    $total35Umum=0;
    $total36Umum=0;
    $total37Umum=0;
    $total38Umum=0;
    $total39Umum=0;
    
    $total40Umum=0;
    $total40BPJS=0;
    $total40Gratis=0;

    $total1BPJS=0;
    $total3BPJS=0;
    $total2BPJS=0;
    $total4BPJS=0;
    $total5BPJS=0;
    $total6BPJS=0;
    $total7BPJS=0;
    $total8BPJS=0;
    $total9BPJS=0;
    $total10BPJS=0;
    $total11BPJS=0;
    $total12BPJS=0;
    $total13BPJS=0;
    $total14BPJS=0;
    $total15BPJS=0;
    $total16BPJS=0;
    $total17BPJS=0;
    $total18BPJS=0;
    $total19BPJS=0;
    $total20BPJS=0;
    $total21BPJS=0;
    $total22BPJS=0;
    $total23BPJS=0;
    $total24BPJS=0;
    $total25BPJS=0;
    $total26BPJS=0;
    $total27BPJS=0;
    $total28BPJS=0;
    $total29BPJS=0;
    $total30BPJS=0;
    $total31BPJS=0;
    $total32BPJS=0;
    $total33BPJS=0;
    $total34BPJS=0;
    $total35BPJS=0;
    $total36BPJS=0;
    $total37BPJS=0;
    $total38BPJS=0;
    $total39BPJS=0;
    
    $total40Umum=0;
    $total40BPJS=0;
    $total40Gratis=0;
    
    $total1Gratis=0;
    $total2Gratis=0;
    $total3Gratis=0;
    $total4Gratis=0;
    $total5Gratis=0;
    $total6Gratis=0;
    $total7Gratis=0;
    $total8Gratis=0;
    $total9Gratis=0;
    $total10Gratis=0;
    $total11Gratis=0;
    $total12Gratis=0;
    $total13Gratis=0;
    $total14Gratis=0;
    $total15Gratis=0;
    $total16Gratis=0;
    $total17Gratis=0;
    $total18Gratis=0;
    $total19Gratis=0;
    $total20Gratis=0;
    $total21Gratis=0;
    $total22Gratis=0;
    $total23Gratis=0;
    $total24Gratis=0;
    $total25Gratis=0;
    $total26Gratis=0;
    $total27Gratis=0;
    $total28Gratis=0;
    $total29Gratis=0;
    $total30Gratis=0;
    $total31Gratis=0;
    $total32Gratis=0;
    $total33Gratis=0;
    $total34Gratis=0;
    $total35Gratis=0;
    $total36Gratis=0;
    $total37Gratis=0;
    $total38Gratis=0;
    $total39Gratis=0;
    
    $total40Umum=0;
    $total40BPJS=0;
    $total40Gratis=0;
    
    $pedodo1="SELECT * from endodonti WHERE tgl >= '$tgl1'AND tgl <= '$tgl2' AND status='Umum' ORDER BY tgl ASC";
    $pedodo2="SELECT * from endodonti WHERE tgl >= '$tgl1'AND tgl <= '$tgl2' AND status='BPJS' ORDER BY tgl ASC";
    $pedodo3="SELECT * from endodonti WHERE tgl >= '$tgl1'AND tgl <= '$tgl2' AND status='Gratis' ORDER BY tgl ASC";
    $EXpedodo1=mysqli_query($link,$pedodo1);
    $EXpedodo2=mysqli_query($link,$pedodo2);
    $EXpedodo3=mysqli_query($link,$pedodo3);
    
    if (mysqli_num_rows($EXpedodo1)>0) {
        while ($data=mysqli_fetch_assoc($EXpedodo1)) {
            $total1Umum+=$data['ip1'];
            $total2Umum+=$data['ip2'];
            $total3Umum+=$data['ip3'];
            $total4Umum+=$data['ip4'];
            $total5Umum+=$data['ip5'];
            $total6Umum+=$data['ip6'];
            $total7Umum+=$data['ip7'];
            $total8Umum+=$data['ip8'];
            $total9Umum+=$data['ip9'];
            $total10Umum+=$data['ip10'];
            $total11Umum+=$data['ip11'];
            $total12Umum+=$data['ip12'];
            $total13Umum+=$data['ip13'];
            $total14Umum+=$data['ip14'];
            $total15Umum+=$data['ip15'];
            $total16Umum+=$data['ip16'];
            $total17Umum+=$data['ip17'];

            $total18Umum+=$data['ip18'];
            $total19Umum+=$data['ip19'];
            $total20Umum+=$data['ip20'];
            $total21Umum+=$data['ip21'];
            $total22Umum+=$data['ip22'];
            $total23Umum+=$data['ip23'];
            $total24Umum+=$data['ip24'];
            $total25Umum+=$data['ip25'];
            $total26Umum+=$data['ip26'];
            $total27Umum+=$data['ip27'];
            $total28Umum+=$data['ip28'];
            $total29Umum+=$data['ip29'];
            $total30Umum+=$data['ip30'];
            $total31Umum+=$data['ip31'];
            $total32Umum+=$data['ip32'];
            $total33Umum+=$data['ip33'];
            $total34Umum+=$data['ip34'];
            $total35Umum+=$data['ip35'];
            $total36Umum+=$data['ip36'];
            $total37Umum+=$data['ip37'];
            $total38Umum+=$data['ip38'];
            $total39Umum+=$data['ip39'];
        }
    }

    if (mysqli_num_rows($EXpedodo2)>0) {
        while ($data=mysqli_fetch_assoc($EXpedodo2)) {
            $total1BPJS+=$data['ip1'];
            $total2BPJS+=$data['ip2'];
            $total3BPJS+=$data['ip3'];
            $total4BPJS+=$data['ip4'];
            $total5BPJS+=$data['ip5'];
            $total6BPJS+=$data['ip6'];
            $total7BPJS+=$data['ip7'];
            $total8BPJS+=$data['ip8'];
            $total9BPJS+=$data['ip9'];
            $total10BPJS+=$data['ip10'];
            $total11BPJS+=$data['ip11'];
            $total12BPJS+=$data['ip12'];
            $total13BPJS+=$data['ip13'];
            $total14BPJS+=$data['ip14'];
            $total15BPJS+=$data['ip15'];
            $total16BPJS+=$data['ip16'];
            $total17BPJS+=$data['ip17'];
            
            $total18BPJS+=$data['ip18'];
            $total19BPJS+=$data['ip19'];
            $total20BPJS+=$data['ip20'];
            $total21BPJS+=$data['ip21'];
            $total22BPJS+=$data['ip22'];
            $total23BPJS+=$data['ip23'];
            $total24BPJS+=$data['ip24'];
            $total25BPJS+=$data['ip25'];
            $total26BPJS+=$data['ip26'];
            $total27BPJS+=$data['ip27'];
            $total28BPJS+=$data['ip28'];
            $total29BPJS+=$data['ip29'];
            $total30BPJS+=$data['ip30'];
            $total31BPJS+=$data['ip31'];
            $total32BPJS+=$data['ip32'];
            $total33BPJS+=$data['ip33'];
            $total34BPJS+=$data['ip34'];
            $total35BPJS+=$data['ip35'];
            $total36BPJS+=$data['ip36'];
            $total37BPJS+=$data['ip37'];
            $total38BPJS+=$data['ip38'];
            $total39BPJS+=$data['ip39'];
    
        }
    }

    if (mysqli_num_rows($EXpedodo2)>0) {
        while ($data=mysqli_fetch_assoc($EXpedodo2)) {
            $total1Gratis+=$data['ip1'];
            $total2Gratis+=$data['ip2'];
            $total3Gratis+=$data['ip3'];
            $total4Gratis+=$data['ip4'];
            $total5Gratis+=$data['ip5'];
            $total6Gratis+=$data['ip6'];
            $total7Gratis+=$data['ip7'];
            $total8Gratis+=$data['ip8'];
            $total9Gratis+=$data['ip9'];
            $total10Gratis+=$data['ip10'];
            $total11Gratis+=$data['ip11'];
            $total12Gratis+=$data['ip12'];
            $total13Gratis+=$data['ip13'];
            $total14Gratis+=$data['ip14'];
            $total15Gratis+=$data['ip15'];
            $total16Gratis+=$data['ip16'];
            $total17Gratis+=$data['ip17'];

            $total18Gratis+=$data['ip18'];
            $total19Gratis+=$data['ip19'];
            $total20Gratis+=$data['ip20'];
            $total21Gratis+=$data['ip21'];
            $total22Gratis+=$data['ip22'];
            $total23Gratis+=$data['ip23'];
            $total24Gratis+=$data['ip24'];
            $total25Gratis+=$data['ip25'];
            $total26Gratis+=$data['ip26'];
            $total27Gratis+=$data['ip27'];
            $total28Gratis+=$data['ip28'];
            $total29Gratis+=$data['ip29'];
            $total30Gratis+=$data['ip30'];
            $total31Gratis+=$data['ip31'];
            $total32Gratis+=$data['ip32'];
            $total33Gratis+=$data['ip33'];
            $total34Gratis+=$data['ip34'];
            $total35Gratis+=$data['ip35'];
            $total36Gratis+=$data['ip36'];
            $total37Gratis+=$data['ip37'];
            $total38Gratis+=$data['ip38'];
            $total39Gratis+=$data['ip39'];
        }
    }
?>